language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "dPB/VzkmtTqow+xvuuRq/EMFNhzZLgYZYb9R308k1bXczJ1BIJ+l/nfu4YG5vUR2A2jkZtywPYsgVU12H1ckz/sbHzhvPc8/0FftSkwzAkQNjApAAeeCvTElRQ+4D7anIRGGBDViNUH6Wo48K0M8xJaL8QddaepfVK67TBzyN6VUU/N8kgY0pMYRS373JqXYcEmA0H4cwg2gIo23PUO5kFz6GMThqStb0H05eu2rnFvvIOfCCVm0iWPj7bApJV2BSJnqrT2iHqhv4cOCTAls921As5e7uKO2fV+0uiX1NyPOWw00ua47yzSTBNMGZZ30fDRiwDddhzT8PungRx3xCt008IUiSAlaZYXX9iDKXOKUcdCr6EKDimNeBYdocjOnCcJQ2vIrh9eCLHKP/bu9LMimBXKvnxDgqYJF2mLARjOZE7mRiWi6eIAM64Khbh2rY7wrQrnqxVYrsXASgvzUtCUAwHZV71asF/Aq96laxHK0f8waDMgPzyE1wY/gRzbhRrANKeFyBi6tv0KOBxAyN9GWXh4wp0RXLzlhNLFxvmUejR00datOM1gzODQRhOnBANeGi1a9YHhnTqmOyC8HiuoC2NhM/aaYBRBycCCh4+0U0uOhjdiYCMJCptzsVi7WOsZTocIYqMlVAZb7dm+kj0IBc2c2nfwrhLBU0bDcsLQ="
  api_key: # c946
    secure: "DtCP4qrv4GyHCKlr/oWfr/0NIVukvd71CNUFmhhwPGBHcDxqhQJ9W8XsA72Oe4N1gbIXCKZrLjj3lbWBmqbumqb47AJyg8l+ur4N46stZYv5yUjj/aMTUFuLKpEXHDuducOpTB9xzeEp2BtFoBdjUmwX9bjATBLehqqwvCSxBNLpr0cmJO6mHFe7X45euGik31ERn+RsvzsIhqXzmKuql+mfjVXMNl3nCvP54y93sGGzOMu47wipydrsE1fYd/TzrSZyAiIePnbOxIqceo0O2NRoo4msVdQR72MX/pdxeFQyyarjcfrnx2uTO+7Wrro46mUuJ3fhS0Wovi2L5MGU1qfAh/s9/tx7IxMnIyc5CgfrYysba2lwotjG6QM4Nm7y9OeTtlm/6l/Efv2ZbpqUFJltlkQOy7Jo/MdT2mWavSSXpURRwRIUScjmPznkUZtlUeT8diefndOb0AOeG4CBuWXtHYTqQAnA4SXmNwsrS3iQdFzmVMJG+4nsSZ/xv863fOT9KVnq80YlAqBZmaQQP7cAhS8KrR7S37KzcseaD+siZBcT1o6ggq8Dy6Q10RendoWpntcwMvqxSdEg7mrDAolJXEk+FCmBYXymm3lw42suivBV2R85zAQyHz/JEaSjnmWGqZZfegONv17KLih6PauhBWzoQrqRL39nDkOnEX8="
  on:
    tags: true
    node: lts/*
